import '../../public/globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import ConditionalHeaderFooter from "@/components/ConditionalHeaderFooter";

export const metadata = {
  title: 'E-commerce App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ConditionalHeaderFooter>
          <main>{children}</main>
        </ConditionalHeaderFooter>
      </body>
    </html>
  );
}